import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'
import { useState, useEffect } from 'react'
import { usePera } from '../../src/contexts/usePera'

export default function Home() {
    const {accountAddress, handleConnectWalletClick, handleDisconnectWalletClick } = usePera()
    const isConnectedToPeraWallet = accountAddress?.length;

    const toggleConnectWallet = () => {
        const toggle = isConnectedToPeraWallet ? handleDisconnectWalletClick : handleConnectWalletClick
        return toggle

    }


    return (
        <div className={styles.container}>
        <Head>
            <title>Algorand Beaker App Template with NextJS</title>
            <meta name="description" content="Generated by create next app" />
        </Head>

        <main className={styles.main}>
            <h1 className={styles.title}>
                KoiFi Protocol
            </h1>

            <p className={styles.description}>
            Let's test an app call to a local network{' '}
            <code className={styles.code}>Hello Beaker</code>
            </p>

            <button onClick={toggleConnectWallet()}> <h2>{isConnectedToPeraWallet ? 'Disconnect' : 'Connect with pera wallet'}</h2> </button><br/>
            <p className={styles.description}>
                {accountAddress}
            </p>
        </main>

        <footer className={styles.footer}>
            <a
            href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
            >
            Powered by{' '}
            <span className={styles.logo}>
                <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
            </span>
            </a>
        </footer>
        </div>
    )
}
